# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Seeds for the STore table
Store.create(name: 'ST KATHARINES WAY EXPRESS',address:'ST KATHARINES WAY EXPRESS',lat:'51.506826',long:'-0.072624',location_id:'52ce9bad42632be6e1e8c992',store_distance:'0.3083144404782735',store_type:'Express')
Store.create(name: 'MANSELL STREET EXPRESS',address:'MANSELL STREET EXPRESS',lat:'51.51201268',long:'-0.073404789',location_id:'52ce9bad42632be6e1e8d03b',store_distance:'0.43127890942798386',store_type:'Express')
Store.create(name: 'TOOLEY STREET METRO',address:'TOOLEY STREET METRO',lat:'51.50416048',long:'-0.081531428',location_id:'52ce9bad42632be6e1e8d1e3',store_distance:'0.6136432287768385',store_type:'Metro')
Store.create(name: 'MONUMENT METRO',address:'MONUMENT METRO',lat:'51.51058405',long:'-0.085008521',location_id:'52ce9bad42632be6e1e8cd98',store_distance:'0.6561243089876169',store_type:'Metro')
Store.create(name: 'LONDON ST. BOTOLPHS EXPRESS',address:'LONDON ST. BOTOLPHS EXPRESS',lat:'51.51442573',long:'-0.076877281',location_id:'52ce9bad42632be6e1e8d176',store_distance:'0.6583359778213261',store_type:'Express')

# Seeds for the Products

Product.create(name:'Tesco RedWine',description:'[\"Red wine vinegar\", \"Ideal for dressings, sauces & marinades\"]',price:'0.229',tpnb:'50342734')
Product.create(name:'Diet Coke',description:'[\"Sparkling Low Calorie Soft Drink with Vegetable Extracts with Sweeteners\"]',price:'0.253',tpnb:'51580421')
Product.create(name:'Weetabix Milk',description:'[\"Mixed Cereal Bar Drizzled with a Milk Chocolate Coating.\"]',price:'1.47',tpnb:'64252462')
Product.create(name:'Woodwards GripeWater',description:'[\"Gripe Water Dual Action\"]',price:'2.0',tpnb:'50085963')
Product.create(name:'Carrs Biscuits',description:'[\"Crackers.\"]',price:'0.495',tpnb:'50737711')
Product.create(name:'Banana Biscuits',description:'[\"Bite-sized crunchy slices of real banana\", \"Did you know...? A bunch of bananas is known as a hand.\", \"For more info and find us on Facebook to hear what other mums & dads think about our products.\"]',price:'40.0',tpnb:'63719235')
Product.create(name:'Milkybar Chocolate',description:'[\"White chocolate.\", \"www.facebook.com/milkybar\", \"Good to rememb r\", \"Enjoying chocolate as part of a varied, balanced diet and a healthy lifestyle, is one of lifes little pleasures.\"]',price:'1.75',tpnb:'60664044')

#COKE
Product.create(name:'Bread Rolls',description:'[\"Seasoned pork sausage meat wrapped in puff pastry.\", \"Everyday Value 8 Sausage Rolls\"]',price:'0.208',tpnb:'55537485')
Product.create(name:'Coca Cola',description:'[\"Did you know every time you open a bottle of Coca Cola 12,607 bubbles are born?  Happy Birthday bubbles\", \"Very low sodium\", \"Great Coke taste\", \"Natural flavours\", \"No added preservatives\", \"Suitable for vegetarians/vegans\", \"Serve ice cold for maximum refreshment.\", \"Contains 4 X 2ltr bottles\", \"Storage\", \"Keep cold in the fridge.\", \"Please recycle.\"]',price:'0.084',tpnb:'53043202')
Product.create(name:'Coke Zero',description:'[\"Sparkling Low Calorie Soft Drink with Vegetable Extracts with Sweeteners\"]',price:'0.05',tpnb:'59202529')
Product.create(name:'Cherry Coke 2 Litre Bottle',description:'[\"For more information on this product log onto www.coca cola.co.uk\"]',price:'0.05',tpnb:'50196941')

#WINES

Product.create(name:'Weight Watcher RedWine',description:'[\"Signature Recipes Beef & Red Wine Casserole.\", \"Tender beef with vegetables soaked in a rich red wine gravy, topped with crispy potatoes.\", \"This meal contains 1 of your 5 a day when eaten as part of a healthy balanced diet.\", \"7 ProPoints value® per meal.\", \"WEIGHT WATCHERS FROM HEINZ.\", \"WEIGHT WATCHERS on foods and beverages is the registered trademark of WW Foods, LLC.\", \"WEIGHT WATCHERS for services and ProPoints are the registered trademarks of Weight Watchers International, Inc.\", \"Trademarks are used under licence.\", \"© 2012 Weight Watchers International, Inc. All rights reserved.\"]',price:'6.25',tpnb:'64161287')
Product.create(name:'Chianti Wine',description:'[\"Roll of egg pasta filled with a beef and tomato sauce\", \"Slow cooked english beef ragu braised with a selection of vegetables, herbs and Italian tomatoes and finished with red wine, stuffed into a rolls of Italian free range egg pasta.\"]',price:'9.73',tpnb:'56407131')
Product.create(name:'RedWine Ravioli',description:'[\"Egg pasta parcels with beef and red wine filling\"]',price:'5.0',tpnb:'58670678')
Product.create(name:'Green Ginger Wine',description:'[\"Ginger Wine\", \"British Wine\"]',price:'3.75',tpnb:'50339042')
Product.create(name:'WhiteWine Vinegar',description:'[\"Classic White Wine Vinegar\", \"For recipe ideas, visit www.aspall.co.uk\"]',price:'0.4',tpnb:'59140832')
Product.create(name:'Weetabix Chocolate',description:'[\"Hot Oat Cereal with Chocolate, fortified with vitamins, iron and calcium.\"]',price:'0.444',tpnb:'61717183')
Product.create(name:'Aspall OrganicWine',description:'[\"Organic White Wine Vinegar\", \"For recipe ideas, visit www.aspall.co.uk\"]',price:'0.486',tpnb:'54039546')

#APPLES

Product.create(name:'Braeburn Apples',description:'[\"Tesco Braeburn Apples Loose\"]',price:'2.0',tpnb:'50852666')
Product.create(name:'Bramley Apples',description:'[\"Tesco Bramley Apples\"]',price:'1.6',tpnb:'50501282')
Product.create(name:'Cox Apples',description:'[\"Apples, Cox\"]',price:'2.0',tpnb:'50925828')
Product.create(name:'Gala Apples',description:'[\"Tesco Gala Apples\"]',price:'2.0',tpnb:'50623419')
Product.create(name:'Copella Apple Juice',description:'[\"Apple Juice.\"]',price:'0.397',tpnb:'56447288')
Product.create(name:'PinkLady Apples',description:'[\"Apples, Pink Lady\"]',price:'2.75',tpnb:'52528656')
Product.create(name:'Pressed Apple Juice',description:'[\"Pressed apple juice.\", \"Our never from concentrate juice comes straight from the fruit and we want it to taste just as fresh. Thats why its pressed and then lightly pasteurised and carefully bottled ready for drinking. All you are getting is the bright taste of perfectly ripe fruit. Into each bottle we press 8 apples.\"]',price:'0.14',tpnb:'51577823')
Product.create(name:'Granny Smith Apples',description:'[\"Apples Granny Smith\"]',price:'2.0',tpnb:'50500219')

#BANANA

Product.create(name:'EverydayValue Bananas',description:'[\"Everyday Value Bananas\"]',price:'0.144',tpnb:'62984451')
Product.create(name:'Frijj Banana Milkshake',description:'[\"High temperature pasteurised low fat banana milkshake\"]',price:'0.138',tpnb:'51665765')
Product.create(name:'Muller Light Banana',description:'[\"Smooth banana & custard flavour fat free yogurt with sugars & sweeteners\"]',price:'0.389',tpnb:'58768569')
Product.create(name:'Whitworths Banana Chips',description:'[\"Sweetened and cooked banana chips\", \"Banana Chips are a delicious snack and an ideal topping for cereal, but if you fancy being more adventurous, they are also really versatile, try our delicious simple recipe below or go to our website for more recipe ideas.\", \"For more information and recipes: www.whitworths.co.uk\"]',price:'10.0',tpnb:'51858036')
Product.create(name:'Kiddylicious Banana Bites',description:'[\"Bite-sized crunchy slices of real banana\", \"Did you know...? A bunch of bananas is known as a hand.\", \"For more info and find us on Facebook to hear what other mums & dads think about our products.\"]',price:'40.0',tpnb:'63719235')

#SAUCE

Product.create(name:'Baked Beans Sauce',description:'[\"Baked beans in tomato sauce.\"]',price:'1.14',tpnb:'50020430')
Product.create(name:'Everyday Tomato Sauce',description:'[\"Baked beans in tomato sauce\"]',price:'0.571',tpnb:'51627961')
Product.create(name:'Dolmio Chilli PastaSauce',description:'[\"Intense Tomato Sauce.\", \"Have you had your DOLMIO day? What did you think?\", \"Let us know  The DOLMIO family loves to talk.\"]',price:'0.358',tpnb:'52990314')
Product.create(name:'Everyday Chilli Sauce',description:'[\"Chicken meatballs in tomato sauce.\"]',price:'1.03',tpnb:'57351735')
Product.create(name:'Everyday Brown Sauce',description:'[\"Brown sauce with sugar and sweetener.\", \"Tasted and approved by customers\"]',price:'0.052',tpnb:'51271793')
Product.create(name:'Everyday Spaghetti TomatoSauce',description:'[\"Spaghetti in Tomato Sauce\"]',price:'0.488',tpnb:'51627949')
Product.create(name:'Heinz Tomato Sauce',description:'[\"Baked beans in a deliciously rich tomato sauce.\"]',price:'3.0',tpnb:'50020499')

Product.create(name:'StayFresh Wholemeal Bread',description:'[\"Medium sliced wholemeal bread.\"]',price:'0.075',tpnb:'53295237')
Product.create(name:'Warburtons Toastie Sliced White Bread 400G',description:'[\"Thick sliced white bread\", \"Visit us at: facebook.com/warburtons\"]',price:'0.198',tpnb:'50688895')

# Seeds for the Store Products

StoreProduct.create(product_id: 1, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 1, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 1, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 1, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 2, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 2, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 2, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 2, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 3, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 3, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 3, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 3, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 3, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 4, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 4, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 4, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 4, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 5, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 5, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 5, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 5, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 6, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 6, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 6, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 6, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 7, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 7, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 7, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 7, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 8, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 8, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 8, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 8, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 8, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 9, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 9, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 9, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 9, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 10, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 10, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 10, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 10, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 11, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 11, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 11, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 11, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 12, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 12, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 12, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 12, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 13, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 13, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 13, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 13, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 13, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 14, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 14, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 14, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 14, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 15, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 15, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 15, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 15, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 16, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 16, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 16, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 16, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 17, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 17, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 17, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 17, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 18, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 18, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 18, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 18, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 18, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 19, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 19, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 19, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 19, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 20, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 20, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 20, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 20, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 21, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 21, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 21, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 21, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 22, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 22, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 22, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 22, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 23, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 23, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 23, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 23, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 23, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 24, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 24, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 24, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 24, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 25, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 25, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 25, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 25, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 26, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 26, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 26, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 26, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 27, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 27, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 27, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 27, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 28, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 28, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 28, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 28, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 28, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 29, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 29, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 29, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 29, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 30, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 30, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 30, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 30, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 31, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 31, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 31, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 31, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 32, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 32, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 32, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 32, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 33, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 33, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 33, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 33, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 33, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 34, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 34, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 34, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 34, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 35, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 35, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 35, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 35, store_id: 4, quantity: 10, available: true)

StoreProduct.create(product_id: 36, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 36, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 36, store_id: 4, quantity: 20, available: true)
StoreProduct.create(product_id: 36, store_id: 5, quantity: 30, available: true)
StoreProduct.create(product_id: 37, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 37, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 37, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 37, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 38, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 38, store_id: 2, quantity: 5, available: true)
StoreProduct.create(product_id: 38, store_id: 3, quantity: 5, available: true)
StoreProduct.create(product_id: 38, store_id: 4, quantity: 10, available: true)
StoreProduct.create(product_id: 38, store_id: 5, quantity: 10, available: true)
StoreProduct.create(product_id: 39, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 39, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 39, store_id: 3, quantity: 10, available: true)
StoreProduct.create(product_id: 39, store_id: 5, quantity: 40, available: true)
StoreProduct.create(product_id: 40, store_id: 1, quantity: 10, available: true)
StoreProduct.create(product_id: 40, store_id: 2, quantity: 20, available: true)
StoreProduct.create(product_id: 40, store_id: 3, quantity: 30, available: true)
StoreProduct.create(product_id: 40, store_id: 4, quantity: 10, available: true)